tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-tint": "#99f7ff",
                "primary-dim": "#00e2ee",
                "on-error-container": "#ffa8a3",
                "inverse-primary": "#006a70",
                "secondary-fixed": "#00fc40",
                "on-background": "#ffffff",
                "tertiary-container": "#4da8fe",
                "outline-variant": "#494847",
                "on-primary": "#005f64",
                "primary-fixed": "#00f1fe",
                "on-tertiary-fixed": "#001930",
                "surface-container-high": "#201f1f",
                "surface-bright": "#2c2c2c",
                "surface-container-highest": "#262626",
                "on-secondary-fixed-variant": "#006513",
                "primary-container": "#00f1fe",
                "error": "#ff716c",
                "on-primary-fixed": "#004145",
                "on-primary-container": "#00555a",
                "surface": "#0e0e0e",
                "secondary-dim": "#00ec3b",
                "on-secondary": "#005a10",
                "on-surface": "#ffffff",
                "tertiary-dim": "#47a2f8",
                "on-primary-fixed-variant": "#006065",
                "surface-dim": "#0e0e0e",
                "background": "#0e0e0e",
                "secondary-fixed-dim": "#00ec3b",
                "on-secondary-container": "#e6ffdc",
                "surface-variant": "#262626",
                "secondary-container": "#006e16",
                "inverse-surface": "#fcf8f8",
                "on-surface-variant": "#adaaaa",
                "surface-container-low": "#131313",
                "tertiary-fixed": "#6fb5ff",
                "outline": "#777575",
                "surface-container-lowest": "#000000",
                "surface-container": "#1a1919",
                "on-tertiary": "#003258",
                "on-tertiary-fixed-variant": "#003b66",
                "tertiary": "#6fb5ff",
                "on-error": "#490006",
                "error-dim": "#d7383b",
                "primary": "#99f7ff",
                "on-tertiary-container": "#002746",
                "on-secondary-fixed": "#00440a",
                "secondary": "#00fc40",
                "inverse-on-surface": "#565554",
                "primary-fixed-dim": "#00e2ee",
                "error-container": "#9f0519",
                "tertiary-fixed-dim": "#4da8fe"
            },
            fontFamily: {
                "headline": ["Space Grotesk"],
                "body": ["Inter"],
                "label": ["Space Grotesk"]
            },
            borderRadius: { "DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px" },
        },
    },
}